---
- name: "update cache"
  become: true
  apt:
    update_cache: yes

- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: "remove unnecessary depedencies"
  become: true
  apt:
    autoremove: true

- name: "Run a shell command to get node"
  become: true
  shell: 'curl -fsSL https://deb.nodesource.com/setup_13.x | sudo -E bash -'
    
- name: "install dependencies"
  become: true
  apt: name={{ item }} state=present
  with_items:
    - nodejs
    - npm

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes