---
- name: Creates directory
  file:
    path: ~/app
    state: directory

- name: Get artifacts
  unarchive:
    src: artifact.tar.gz
    dest: ~/app

- name: Creates remote environment
  shell: |
    echo "NODE_ENV=production" > .env
    echo "VERSION=1" >> .env
    echo "TYPEORM_CONNECTION=postgres" >> .env
    echo "TYPEORM_MIGRATIONS_DIR="./src/migrations" >> .env
    echo "TYPEORM_MIGRATIONS=./src/migrations/*.ts" >> .env
    echo "TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.js" >> .env
    echo "TYPEORM_HOST=$TYPEORM_HOST" >> .env
    echo "TYPEORM_PORT=$TYPEORM_PORT" >> .env
    echo "TYPEORM_USERNAME=$TYPEORM_USERNAME" >> .env
    echo "TYPEORM_PASSWORD=$TYPEORM_PASSWORD" >> .env
    echo "TYPEORM_DATABASE=$TYPEORM_DATABASE" >> .env


- name: Start app
  shell: |
    sudo npm install
    sudo pm2 stop default
    sudo pm2 start npm --start
  args:
    chdir: ~/app
  